[build]
  publish = 'out'
  command = 'yarn export'

[[plugins]]
  package = '@netlify/plugin-lighthouse'

[functions]
  directory = './server/functions/'
  node_bundler = 'esbuild'

[dev]
  functionsPort = 9999

[[redirects]]
  from = '/'
  to = '/page/1'
  status = 200

[[redirects]]
  from = '/'
  query = { page = ":page" }
  to = '/page/:page'
  status = 200
