[build]
  publish = '.next'
  command = 'yarn build'

[[plugins]]
  package = '@netlify/plugin-lighthouse'

[functions]
  directory = './server/functions/'
  node_bundler = 'esbuild'

[dev]
  functionsPort = 9999
