[build]
  publish = 'out'
  command = 'yarn export'

[functions]
  directory = './server/functions/'
  node_bundler = 'esbuild'

[dev]
  functionsPort = 9999

[[redirects]]
  from = '/'
  to = '/page/1'
  status = 200
