[build]
  base = './'
  publish = 'out'
  command = 'yarn export'

[[plugins]]
  package = '@netlify/plugin-lighthouse'

[functions]
  directory = 'functions/'
  node_bundler = 'esbuild'

[dev]
  functionPort = 7200
