/* eslint-disable */
export const dishes = [
  "Vegan Pad Thai",
  "Avocado Toast",
  'Chana Masala',
  'Hummus',
  'Falafel',
  'Caprese Salad',
  'Guacamole',
  'Veggie Burger',
  'Tofu Scramble',
  'Vegan Mac and Cheese',
  'Spicy Lentil Soup',
  'Pesto Pasta',
  'Tomato Soup',
  'Butternut Squash Soup',
  "Vegan BBQ Pulled Jackfruit Sandwich",
  "Cauliflower Buffalo Wings",
  "Vegan Chickpea Curry",
  "Vegan Meatball Sub",
  "Mushroom and Lentil Bolognese",
  "Vegan Caesar Salad",
  "Sweet Potato and Black Bean Enchiladas",
  "Vegan Pad Thai",
  "Tofu Scramble",
  "Vegan Sushi Rolls",
  "Chickpea Flour Omelette",
  "Quinoa Stuffed Bell Peppers",
  "Vegan Shepherd's Pie",
  "Chickpea Salad Sandwich",
  "Vegan Lentil Soup",
  "Zucchini Noodles with Avocado Pesto",
  "Vegan Buffalo Cauliflower Pizza",
  "Vegan Spinach and Artichoke Dip",
  "Vegan Falafel Wrap",
  "Coconut Curry Tofu",
  "Vegan Mushroom Risotto",
  "Vegan Sloppy Joes",
  "Crispy Tofu Stir-Fry",
  "Vegan Stuffed Mushrooms",
  "Vegan Eggplant Parmesan",
  "Quinoa and Black Bean Burgers",
  "Vegan Tacos",
  "Vegan Lentil Loaf",
  "Roasted Vegetable Quinoa Salad",
  "Vegan Mushroom Stroganoff",
  "Vegan Chickpea Salad",
  "Vegan Mac and Cheese",
  "Vegan Broccoli and Cheese Soup",
  "Cauliflower Fried Rice",
  "Vegan Teriyaki Tempeh",
  "Vegan Black Bean Brownies",
  "Vegan Caprese Salad",
  "Vegan Greek Salad",
  "Vegan Spinach Lasagna",
  "Vegan Zucchini Bread",
  "Vegan Baked Beans",
  "Vegan BBQ Tofu Skewers",
  "Vegan Pesto Pasta",
  "Vegan Sweet and Sour Cauliflower",
  "Vegan Butternut Squash Soup",
  "Vegan Cornbread",
  "Vegan Chickpea Tikka Masala",
  "Vegan Caesar Dressing",
  "Vegan Cashew Cheese",
  "Vegan Chocolate Chip Cookies",
  "Vegan Peanut Butter Cups",
  "Vegan Coconut Curry",
  "Vegan Ratatouille",
  "Vegan Mushroom Soup",
  "Vegan Chickpea Tacos",
  "Vegan Lentil Meatballs",
  "Vegan Spinach and Feta Stuffed Peppers",
  "Vegan Lemon Bars",
  "Vegan Pecan Pie",
  "Vegan Thai Green Curry",
  "Vegan Caprese Sandwich",
  "Vegan Buffalo Cauliflower Salad",
  "Vegan Quinoa Salad",
  "Vegan Chocolate Mousse",
  "Vegan Pumpkin Soup",
  "Vegan Sloppy Lentils",
  "Vegan Stuffed Bell Peppers",
  "Vegan Chickpea Noodle Soup",
  "Vegan Coconut Rice Pudding",
  "Vegan Ratatouille Tart",
  "Vegan Falafel Salad",
  "Vegan Mushroom and Spinach Quiche",
  "Vegan Butternut Squash Risotto",
  "Vegan Zucchini Fritters",
  "Vegan Caesar Wrap",
  "Vegan Spinach and Mushroom Pasta",
  "Vegan Sweet Potato Casserole",
  "Vegan Cashew Alfredo Sauce",
  "Vegan Blueberry Muffins",
  "Vegan Strawberry Shortcake",
  "Vegan Buffalo Cauliflower Wraps",
  "Vegan Lentil Salad",
  "Vegan Chickpea and Vegetable Stir-Fry",
  "Vegan Coconut Curry Noodles",
  "Vegan Ratatouille Pasta",
  "Vegan Falafel Burger",
  "Vegan Mushroom and Lentil Shepherd's Pie",
  "Vegan Lemon Poppy Seed Bread",
  "Vegan Pumpkin Pie",
  "Vegan Thai Red Curry",
  "Vegan Caprese Pasta Salad",
  "Vegan Buffalo Cauliflower Tacos",
  "Vegan Quinoa Stuffed Tomatoes",
  "Vegan Chocolate Avocado Pudding",
  "Vegan Butternut Squash Soup",
  "Vegan Zucchini and Corn Fritters",
  "Vegan Caesar Salad Wraps",
  "Vegan Spinach and Artichoke Pasta",
  "Vegan Sweet Potato Hash",
  "Vegan Cashew Sour Cream",
  "Vegan Banana Bread",
  "Vegan Blueberry Pancakes",
  "Vegan Buffalo Cauliflower Dip",
  "Vegan Lentil Chili",
  "Vegan Chickpea and Spinach Curry",
  "Vegan Coconut Curry Stir-Fry",
  "Vegan Ratatouille Stuffed Peppers",
  "Vegan Falafel Pita",
  "Vegan Mushroom and Walnut Bolognese",
  "Vegan Lemon Pound Cake",
  "Vegan Apple Pie"]
