/* eslint-disable */
export  const dishes = [
   "Vegan Pad Thai",
    "Avocado Toast",
    'Chana Masala',
    'Pad Thai',
    'Hummus',
    'Falafel',
    'Caprese Salad',
    'Guacamole',
    'Veggie Burger',
    'Tofu Scramble',
    'Vegan Mac and Cheese',
    'Spicy Lentil Soup',
    'Pesto Pasta',
    'Tomato Soup',
    'Butternut Squash Soup',
    'Vegetable Curry',
    'Quinoa Salad',
    'Baked Sweet Potato',
    'Stir-Fry',
    'Vegan Lasagna',
    'Cauliflower Wings',
    'Potato Leek Soup',
    'Tomato Bruschetta',
    'Vegetable Stew',
    'Ratatouille',
    'Sweet Potato Curry',
    'Green Smoothie',
    'Vegan Pizza',
    'Vegan Caesar Salad',
    'Vegan Sushi',
    'Vegan Lentil Soup',
    'Vegan Enchiladas',
    'Vegan Tacos',
    'Vegan Fajitas',
    'Vegan Stuffed Peppers',
    'Vegan Mushroom Risotto',
    'Vegan Meatballs',
    'Vegan Tofu Curry',
    'Vegan Spinach and Artichoke Dip',
    'Vegan Nachos',
    'Vegan Eggplant Parmesan',
    'Vegan Roasted Vegetable Pasta',
    'Vegan Mushroom Stroganoff',
    'Vegan Thai Green Curry',
    'Vegan Sweet Potato Tacos',
    'Vegan Philly Cheesesteak',
    'Vegan Potato Salad',
    'Vegan Jackfruit Carnitas',
    'Vegan Kung Pao Tofu',
    'Vegan Tomato Soup',
    "Vegan Mushroom Bourguignon",
    "Vegan Cabbage Rolls",
    "Vegan Lentil Shepherd's Pie",
    "Vegan Coconut Curry",
    "Vegan Tempeh Bacon BLT",
    "Vegan Chickpea Salad",
    "Vegan Jackfruit Pulled Pork Sandwiches",
    "Vegan Broccoli Cheddar Soup",
    "Vegan Lentil Meatloaf",
    "Vegan General Tso's Tofu",
    "Vegan Fettuccine Alfredo",
    "Vegan Portobello Steaks",
    "Vegan Baked Ziti",
    "Vegan Corn Chowder",
    "Vegan Sweet and Sour Tofu",
    "Vegan Ratatouille Tart",
    "Vegan Creamy Tomato Basil Soup",
    "Vegan BBQ Pulled Jackfruit",
    "Vegan Miso Soup",
    "Vegan Greek Salad",
    "Vegan Chickpea Curry",
    "Vegan Spinach Artichoke Stuffed Shells",
    "Vegan Buffalo Cauliflower Wings",
    "Vegan Lentil Bolognese",
    "Vegan Creamy Broccoli Soup",
    "Vegan Korean BBQ Tofu",
    "Vegan Butternut Squash Mac and Cheese",
    "Vegan Black Bean Soup",
    "Vegan Gumbo",
    "Vegan Stuffed Acorn Squash",
    "Vegan Curried Lentil Soup",
    "Vegan Shepherd's Pie with Sweet Potato",
    "Vegan Pumpkin Curry",
    "Vegan Cashew Alfredo",
    "Vegan Sloppy Joes",
    "Vegan Caesar Salad with Tofu",
    "Vegan Cream of Mushroom Soup",
    "Vegan Broccoli Salad",
    "Vegan Mushroom and Lentil Shepherds Pie",
    "Vegan Cucumber Salad",
    "Vegan Tofu Tikka Masala",
    "Vegan Carrot Ginger Soup",
    "Vegan Chickpea Nuggets",
    "Vegan French Onion Soup",
    "Vegan Mushroom and Spinach Quiche",
    "Vegan Pad See Ew",
    "Vegan Lentil Soup with Lemon and Cumin",
    "Vegan Tofu and Vegetable Stir Fry",
    "Vegan Chickpea and Vegetable Curry"
   ]
