name: Publish recipe of the day
on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run test'
        type: environment
        required: true
jobs:
  Run_ansible_playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn 
        run: npm install -g yarn
      - name: Checkout code
        uses: actions/checkout@v3
      - name: switch to repo directory
        run: |
          cd "${{ github.workspace }}"
      - name: Install dependencies
        run: yarn
      - name: Download AI Recipe
        run: yarn ai-recipe-day-download
      - name: Push changes
        uses: golfzaptw/action-commit-push-pr@1.0.2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PREFIX_BRANCHES: 'update'
          DEFAULT_BRANCHES: 'main'
          COMMIT_MESSAGE: 'New AI recipe'
          TITLE_PR: 'Chore: New AI Recipe of the Day'
          BODY_PR: ''
