name: Publish recipe of the day
on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run test'
        required: false
        type: environment
jobs:
  Run_ansible_playbook:
    runs-on: ubuntu-latest
    env:
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: 587
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME  }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      FROM_NAME: ${{ secrets.FROM_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: switch to repo directory
        run: |
          cd "${{ github.workspace }}"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Download AI Recipe
        run: yarn ai-recipe-day-download
      - name: Push changes
        uses: golfzaptw/action-commit-push-pr@1.0.2
        with:
          BODY_PR: ''
          COMMIT_MESSAGE: 'New AI recipe'
          DEFAULT_BRANCHES: 'main'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PREFIX_BRANCHES: 'update'
          TITLE_PR: 'Chore: New AI Recipe of the Day'
