name: Publish recipe of the day
on:
  schedule:
    - cron: '30 5,12,16,21 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run test'
        required: false
        type: environment
jobs:
  download_ai_recipe_of_the_day:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'production'
      GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: 587
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME  }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      FROM_NAME: ${{ secrets.FROM_NAME }}
      PR_PREFIX: "[AUTO AI RECIPE]"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: switch to repo directory
        run: |
          cd "${{ github.workspace }}"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Download AI Recipe
        run: |
          export RECIPE_OUTPUT=$(yarn ai-recipe-day-download)
          echo "RECIPE_OUTPUT<<EOFMARKER" >> ${GITHUB_ENV}
          echo "${RECIPE_OUTPUT}" >> ${GITHUB_ENV}
          echo "EOFMARKER" >> ${GITHUB_ENV}
          echo "${RECIPE_OUTPUT}"
      - name: Add, commit and Push changes
        run: |
          CURRENT_DATE=$(date +"%d%m%Y%H%M")
          BRANCH_NAME="new_ai_recipe_$CURRENT_DATE"
          git config --global user.email "jtn.kathuria@gmail.com"
          git config --global user.name "The Fearless Cooking"
          git add content public
          git checkout -b "$BRANCH_NAME"
          git commit -m "Added AI Recipe : $CURRENT_DATE"
          git push -u origin $(git branch --show-current)
          gh pr create --title "$PR_PREFIX Add with Id: $CURRENT_DATE" --body "${{ env.RECIPE_OUTPUT }}" --label "automerge"
          echo "PR_NUMBER=$(gh pr view --json number --jq '.number')" >> "$GITHUB_ENV"
      # - uses: reitermarkus/automerge@v2
      #   with:
      #     token: ${{ github.token }}
      #     merge-method: squash
      #     squash-title: squash-commit-title
      #     squash-commit-title: ${pull_request.title}
      #     do-not-merge-labels: never-merge
      #     required-labels: automerge
      #     pull-request: ${{ env.PR_NUMBER }}
      #     review: ${{ github.event.inputs.review }}
      #     dry-run: false
      # - name: "Comment when PR is marked as automerge"
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ env.PR_NUMBER }}
      #     body: |
      #       Marking this PR as Automerge. 🚀
